### ISSUE TITLE
Auto indenting checklist break layout

### ISSUE THREAD

**Issue by labe-me** [org-trello/org-trello#266]
Hello and thank you for the org-trello,

I am currently trying to make it work for but I experience a strange bug which doesn't occur with only org-mode.

When I add a checklist to a card and hit Enter the checklist is automatically indented by 2 characters.
If I save the file (after removing the indent) the checklist is indented again.

(And sometimes, while working on a test.trello file)
If I add another checklist or hit Enter again the above checklist is again indented by 2 characters.

When things are not so bad, the produced file looks like this:

```
* TODO Test this stuff
  - [ ] This check list
    - [ ] Test item
      - [ ] and This item
```

When I try to synchronize with trello the check list is converted to an item because of the indent and everything else is trashed.

When I disable org-trello-mode, remove the extra spaces and save I get the expected file without the indent but when I enable org-trello-mode again the extra indent comes back.

And when I edit a regular .org file I don't have the problem and org saves me this:

```
* TODO Test this stuff
- [ ] This check list
  - [ ] Test item
    - [ ] and This item
```

Any idea what could be wrong with my setup?

Note: I use 24.5.1/elpa/org-trello-20150524.428

**Comment by ardumont** [comment]
Hello,

> Hello and thank you for the org-trello,

Thanks!

> I am currently trying to make it work for but I experience a strange bug which doesn't occur with only org-mode.

Assuming you meant, `when not activating org-trello` :D

> When I add a checklist to a card and hit Enter the checklist is automatically indented by 2 characters.

It's a feature!
Seriously though, it's org-trello's way to discriminate between card's description (indented by 2), checklist (indented by 2), item (indented by 4).

> If I save the file (after removing the indent) the checklist is indented again.

Yes, there is a hook installed when org-trello's activated which triggers the reindentation needed for org-trello to understand what you want it to sync back and forth.

> (And sometimes, while working on a test.trello file)
> If I add another checklist or hit Enter again the above checklist is again indented by 2 characters.

Yes.
To avoid you try to sync something that org-trello won't understand, it forces the indentation.
I found no other way to do it simply.

> When things are not so bad, the produced file looks like this:
> 
> * TODO Test this stuff
> - [ ] This check list
>   - [ ] Test item
>     - [ ] and This item

Indeed, there is something wrong.

This should more look like:

```txt
* TODO Test this stuff
  - [ ] This check list
    - [ ] Test item
    - [ ] and This item
```

> When I try to synchronize with trello the check list is converted to an item because of the indent and everything else is trashed.
> 
> When I disable org-trello-mode, remove the extra spaces and save I get the expected file without the indent but when I enable org-trello-mode again the extra indent comes back.
> 
> And when I edit a regular .org file I don't have the problem and org saves me this:
> 
> * TODO Test this stuff
> - [ ] This check list
>   - [ ] Test item
>     - [ ] and This item
>

(I hope the markdown rendering does not mess things up in your representation of the actual state...)

It should be more like:

```txt
* TODO Test this stuff
- [ ] This check list
  - [ ] Test item
  - [ ] and This item
  ```

org-trello understands only what trello needs to understand.
That is card (level 1), checklist (2), item(3) and comment (as in org heading level 2, card is an org heading level 1)

What's deeper than 3 levels is not expected to work (also I do not remember what will happen...)
  
> Any
> 
> idea what could be wrong with my setup?

Not quite.
We must already be ok on the format (hoping for the best regarding the markdown rendering in github).

> Note: I use 24.5.1/elpa/org-trello-20150524.428

Thanks for the detailed report.

Can you please show me the state of the buffer after the sync to trello?

**Comment by labe-me** [comment]
The 3rd level of checkbox was my fault, I made another test with an empty card:

```* TODO New card```

C-c o c => the card is added to trello

below the :PROPERTIES:, no empty line, i start adding a checklist:

```* TODO Test
:PROPERTIES:
:orgtrello-id: 5577efbcdeb870b2fae495d5
:orgtrello-local-checksum: 182d2fe4614fbc4b0f438116cad4a3e2f347f77361e5c05b8935603b0662fc32
:END:
- [ ] checklist <- cursor here
```

I hit ENTER and the checklist is moved 2 chars to the right

```
* TODO Test
:PROPERTIES:
:orgtrello-id: 5577efbcdeb870b2fae495d5
:orgtrello-local-checksum: 182d2fe4614fbc4b0f438116cad4a3e2f347f77361e5c05b8935603b0662fc32
:END:
  - [ ] checklist
```

Cursor on the Card, C-c o c, the checklist is synchronized appropriately, I get

```* TODO Test
:PROPERTIES:
:orgtrello-id: 5577efbcdeb870b2fae495d5
:orgtrello-local-checksum: 17da0788634952b893559f54d3238c14a9f97db9220c508f38a2a0a83fde8a5f
:END:
  - [ ] checklist :PROPERTIES: {"orgtrello-id":"5577f07afc907dec89967911","orgtrello-local-checksum":"0dd1a5faab14bb8c70bd2c38bde9031db3f50ef5e36f919b7622e2670a60d24d"}
```

Now adding a item

```* TODO Test
:PROPERTIES:
:orgtrello-id: 5577efbcdeb870b2fae495d5
:orgtrello-local-checksum: 17da0788634952b893559f54d3238c14a9f97db9220c508f38a2a0a83fde8a5f
:END:
  - [ ] checklist :PROPERTIES: {"orgtrello-id":"5577f07afc907dec89967911","orgtrello-local-checksum":"0dd1a5faab14bb8c70bd2c38bde9031db3f50ef5e36f919b7622e2670a60d24d"}
    - [ ] item a
```

C-c o c on the card, the sync seem to work for a demi-second, the item is added to trello in the checklist and I see some meta data in the org buffer but then the org buffer is modified and the item disappear I get:

```* TODO Test
:PROPERTIES:
:orgtrello-id: 5577efbcdeb870b2fae495d5
:orgtrello-local-checksum: 17da0788634952b893559f54d3238c14a9f97db9220c508f38a2a0a83fde8a5f
:END:
  - [ ] checklist :PROPERTIES: {"orgtrello-id":"5577f0f8ed61f80be33ae568","orgtrello-local-checksum":"0dd1a5faab14bb8c70bd2c38bde9031db3f50ef5e36f919b7622e2670a60d24d"}
```

No more item a in org, this item is still present on trello.

Thanks for the help.

**Comment by ardumont** [comment]
Thanks for the thorough use case.
I will look into it as soon as I found some time.

Cheers,

**Comment by ardumont** [comment]
Hello,

for information, I tried to reproduce this behavior and failed...

Is the disappearing item destroyed from the buffer?

Is you disable org-trello, what happens regarding the item?

(I use overlay to hide metadata...)

Cheers,

**Comment by labe-me** [comment]
Thank you for trying to reproduce the problem.

After sync, the new item appear with the trello meta data, then, a 1/2 second later, it disappear. 
If I disable org-trello-mode after the item disappeared I can see this : 

```
* TODO Another card
:PROPERTIES:
:orgtrello-id: 5586848c2cd7299ccf1387c0
:orgtrello-local-checksum: 49e97f3e09ec1ec350b8ac0455f31ace2351227f86973ed6186a56bda5a4eb8d
:END:
  - [ ] Checklist :PROPERTIES: {"orgtrello-id":"558684c64b8326792dadec63","orgtrello-local-checksum":"4c3758d97f9f5d689176cbe410715b2c16e127949d14ff2e5717f01d653ffa0c"}
```

The item was really removed from the buffer.

Regards 
Laurent

**Comment by ardumont** [comment]
Hello again,

Sorry for the delay.

> The item was really removed from the buffer.

I'm baffled.
Only sync from trello remove things from buffer to write the synced one back.

You may not remember but:
- Was there no message at all in the mini-buffer?
- From trello's side, did the item appeared?

--

Can you please update to the latest 0.7.1, try to reproduce?
If the problem is still here, can you please paste <kbd>M-x org-trello-bug-report</kbd>'s report in here?

Thanks in advance.

Cheers,
